//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionMan.Desktop.Localized {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductionMan.Desktop.Localized.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2014 OrderedSoft. All rights reserved..
        /// </summary>
        public static string AboutAppCopyright {
            get {
                return ResourceManager.GetString("AboutAppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamedMosavi@gmail.com.
        /// </summary>
        public static string AboutAppEmailAddress {
            get {
                return ResourceManager.GetString("AboutAppEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string AboutAppEmailAddressLabel {
            get {
                return ResourceManager.GetString("AboutAppEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProMan.
        /// </summary>
        public static string AboutAppName {
            get {
                return ResourceManager.GetString("AboutAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name:.
        /// </summary>
        public static string AboutAppNameLabel {
            get {
                return ResourceManager.GetString("AboutAppNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutAppVersionLabel {
            get {
                return ResourceManager.GetString("AboutAppVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTR.
        /// </summary>
        public static string AppDir {
            get {
                return ResourceManager.GetString("AppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProMan.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to permanently delete the following record. This process is irrevirsible. Are you sure you want to continue?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ColumnHeaderCulture {
            get {
                return ResourceManager.GetString("ColumnHeaderCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnHeaderDisplayName {
            get {
                return ResourceManager.GetString("ColumnHeaderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ColumnHeaderRole {
            get {
                return ResourceManager.GetString("ColumnHeaderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon!.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day!.
        /// </summary>
        public static string GoodDay {
            get {
                return ResourceManager.GetString("GoodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening!.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day!.
        /// </summary>
        public static string GoodMidDay {
            get {
                return ResourceManager.GetString("GoodMidDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning!.
        /// </summary>
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening!.
        /// </summary>
        public static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string LoadinMessage {
            get {
                return ResourceManager.GetString("LoadinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Signing In.
        /// </summary>
        public static string LoginRetry {
            get {
                return ResourceManager.GetString("LoginRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Materials.
        /// </summary>
        public static string PageTitleMaterials {
            get {
                return ResourceManager.GetString("PageTitleMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permissions.
        /// </summary>
        public static string PageTitlePermissions {
            get {
                return ResourceManager.GetString("PageTitlePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Processes.
        /// </summary>
        public static string PageTitleProcesses {
            get {
                return ResourceManager.GetString("PageTitleProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settings.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Stores.
        /// </summary>
        public static string PageTitleStores {
            get {
                return ResourceManager.GetString("PageTitleStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangage Users.
        /// </summary>
        public static string PageTitleUsers {
            get {
                return ResourceManager.GetString("PageTitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in, please wait....
        /// </summary>
        public static string SigningInMessage {
            get {
                return ResourceManager.GetString("SigningInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server....
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform request. Please see log file for details..
        /// </summary>
        public static string StatusFailedToCreateItem {
            get {
                return ResourceManager.GetString("StatusFailedToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation cancelled due to an error. Please try again or contact administrator in case the issue didn&apos;t resolve itself..
        /// </summary>
        public static string StatusFailedToDeleteItem {
            get {
                return ResourceManager.GetString("StatusFailedToDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update operation cancelled due to an error. Please try again or contact administrator in case the issue didn&apos;t resolve itself..
        /// </summary>
        public static string StatusFailedToUpdatedItem {
            get {
                return ResourceManager.GetString("StatusFailedToUpdatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item created successfuly!.
        /// </summary>
        public static string StatusItemCreated {
            get {
                return ResourceManager.GetString("StatusItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested record deleted successfully!.
        /// </summary>
        public static string StatusItemDeleted {
            get {
                return ResourceManager.GetString("StatusItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item modified successfuly!.
        /// </summary>
        public static string StatusItemUpdated {
            get {
                return ResourceManager.GetString("StatusItemUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed. Changes will take effect next time you open the application..
        /// </summary>
        public static string StatusLanguageChanged {
            get {
                return ResourceManager.GetString("StatusLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TabTitleAbout {
            get {
                return ResourceManager.GetString("TabTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string TabTitleMaterials {
            get {
                return ResourceManager.GetString("TabTitleMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string TabTitlePermissions {
            get {
                return ResourceManager.GetString("TabTitlePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string TabTitleProcesses {
            get {
                return ResourceManager.GetString("TabTitleProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabTitleSettings {
            get {
                return ResourceManager.GetString("TabTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string TabTitleStores {
            get {
                return ResourceManager.GetString("TabTitleStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string TabTitleUsers {
            get {
                return ResourceManager.GetString("TabTitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string WindowTitleLogin {
            get {
                return ResourceManager.GetString("WindowTitleLogin", resourceCulture);
            }
        }
    }
}
